# sphere-api-stack/urbverde-ui/.github/workflows/deploy.yml
name: Deploy UI to Staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: dev  # Explicitly checkout the dev branch

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/urbverde-ui:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/urbverde-ui:latest
        
    - name: Deploy to Staging Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: |
          cd /home/${{ secrets.PRODUCTION_USER }}/sphere-api-stack
          
          # If the 'urbverde-ui' directory does not exist, clone the repository
          if [ ! -d "urbverde-ui" ]; then
            echo "Cloning urbverde-ui repository..."
            git clone -b dev https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/UrbVerde/urbverde-ui.git urbverde-ui
            if [ $? -ne 0 ]; then
              echo "Failed to clone urbverde-ui repository. Exiting."
              exit 1
            fi
          else
            echo "urbverde-ui already exists. Pulling latest changes from dev branch..."
            cd urbverde-ui
            git fetch origin dev
            git reset --hard origin/dev
            cd ..
          fi

          # Pull the latest dev image and restart the UI service
          docker-compose pull urbverde-ui
          docker-compose up -d --force-recreate --no-deps urbverde-ui