name: Fix FilePath First-Line Comments

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  fix_paths:
    name: Correct First-Line FilePath Comments
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Git User
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Run Pathme Logic Inline
        run: |
          PARENT_NAME="$(basename "$(git rev-parse --show-toplevel 2>/dev/null)")"
          if [[ -z "$PARENT_NAME" ]]; then
            DIR_NAME="$(basename "$PWD")"
            echo "Could not determine parent name. Defaulting to $DIR_NAME."
            PARENT_NAME="$DIR_NAME"
          fi

          (echo ".gitignore"; git ls-files) | while read -r FILE; do
            EXT="${FILE##*.}"
            BASENAME="$(basename "$FILE")"
            if [[ "$BASENAME" == ".gitignore" || "$EXT" =~ ^(go|js|ts|html|vue|css|sh|env|yml|yaml|dockerfile|md)$ ]]; then
              if [[ "$BASENAME" == ".gitignore" ]]; then
                COMMENT="# $PARENT_NAME/$BASENAME"
              elif [[ "$EXT" =~ ^(html|vue|md)$ ]]; then
                COMMENT="<!-- $PARENT_NAME/$FILE -->"
              elif [[ "$EXT" == "css" ]]; then
                COMMENT="/* $PARENT_NAME/$FILE */"
              elif [[ "$EXT" =~ ^(sh|env|yml|yaml|dockerfile)$ ]]; then
                COMMENT="# $PARENT_NAME/$FILE"
              else
                COMMENT="// $PARENT_NAME/$FILE"
              fi

              if [[ -s "$FILE" ]]; then
                FIRST_LINE="$(head -n 1 "$FILE" 2>/dev/null)"
                if [[ "$FIRST_LINE" =~ ^([/#<!*]+).*[/[:alnum:]]+/$BASENAME ]]; then
                  if [[ "$FIRST_LINE" != "$COMMENT" ]]; then
                    sed -i "1s|.*|$COMMENT|" "$FILE"
                    echo "Updated wrong path: $FILE"
                  fi
                elif ! grep -q "^$COMMENT" "$FILE" 2>/dev/null; then
                  echo -e "$COMMENT\n$(cat "$FILE")" > "$FILE"
                  echo "Inserted missing path: $FILE"
                fi
              fi
            fi
          done

      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "fix: corrected first-line file path comments via GitHub Actions"
            git push
          else
            echo "No path corrections needed."
          fi
